INSERT IGNORE INTO `#__rsform_components`
(`ComponentId`, `FormId`, `ComponentTypeId`, `Order`, `Published`)
VALUES
(1, 1, 1, 2, 1),
(2, 1, 10, 1, 1),
(3, 1, 1, 3, 1),
(4, 1, 3, 4, 1),
(5, 1, 5, 5, 1),
(6, 1, 4, 6, 1),
(7, 1, 6, 7, 1),
(8, 1, 13, 8, 1),
(9, 1, 10, 9, 1);

INSERT IGNORE INTO `#__rsform_forms` SET
`FormId`=1,
`FormName`='RSformPro example',
`FormLayout`='<div class="componentheading">{global:formtitle}</div>\n{error}\n<table border="0">\n	<tr>\n		<td>{Header:caption}</td>\n		<td>{Header:body}<div class="formClr"/>{Header:validation}</td>\n		<td>{Header:description}</td>\n	</tr>\n	<tr>\n		<td>{FullName:caption} (*)</td>\n		<td>{FullName:body}<div class="formClr"/>{FullName:validation}</td>\n		<td>{FullName:description}</td>\n	</tr>\n	<tr>\n		<td>{Email:caption} (*)</td>\n		<td>{Email:body}<div class="formClr"/>{Email:validation}</td>\n		<td>{Email:description}</td>\n	</tr>\n	<tr>\n		<td>{CompanySize:caption} (*)</td>\n		<td>{CompanySize:body}<div class="formClr"/>{CompanySize:validation}</td>\n		<td>{CompanySize:description}</td>\n	</tr>\n	<tr>\n		<td>{Position:caption} (*)</td>\n		<td>{Position:body}<div class="formClr"/>{Position:validation}</td>\n		<td>{Position:description}</td>\n	</tr>\n	<tr>\n		<td>{ContactBy:caption}</td>\n		<td>{ContactBy:body}<div class="formClr"/>{ContactBy:validation}</td>\n		<td>{ContactBy:description}</td>\n	</tr>\n	<tr>\n		<td>{ContactWhen:caption} (*)</td>\n		<td>{ContactWhen:body}<div class="formClr"/>{ContactWhen:validation}</td>\n		<td>{ContactWhen:description}</td>\n	</tr>\n	<tr>\n		<td>{Submit:caption}</td>\n		<td>{Submit:body}<div class="formClr"/>{Submit:validation}</td>\n		<td>{Submit:description}</td>\n	</tr>\n	<tr>\n		<td>{Footer:caption}</td>\n		<td>{Footer:body}<div class="formClr"/>{Footer:validation}</td>\n		<td>{Footer:description}</td>\n	</tr>\n</table>\n',
`FormLayoutName`='inline',
`FormLayoutAutogenerate`=1,
`FormTitle`='RSForm! Pro example',
`Published`=1,
`Lang`='',
`ReturnUrl`='',
`Thankyou`='<p>Dear {FullName:value},</p><p> thank you for your submission. One of our staff members will contact you by  {ContactBy:value} as soon as possible.</p>',
`UserEmailText`='<p>Dear {FullName:value},</p><p> we received your contact request. Someone will get back to you by {ContactBy:value} soon. </p>',
`UserEmailTo`='{Email:value}',
`UserEmailFrom`='your@email.com',
`UserEmailFromName`='Your Company',
`UserEmailSubject`='Contact confirmation',
`UserEmailMode`=1,
`AdminEmailText`='<p>Customize this e-mail also. You will receive it as administrator. </p><p>{FullName:caption}:{FullName:value}<br />\n{Email:caption}:{Email:value}<br />\n{CompanySize:caption}:{CompanySize:value}<br />\n{Position:caption}:{Position:value}<br />\n{ContactBy:caption}:{ContactBy:value}<br />\n{ContactWhen:caption}:{ContactWhen:value}</p>',
`AdminEmailTo`='youradminemail@email.com',
`AdminEmailFrom`='{Email:value}',
`AdminEmailFromName`='Your Company',
`AdminEmailSubject`='Contact',
`AdminEmailMode`=1;

INSERT IGNORE INTO `#__rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`)
VALUES
(1, 1, 'NAME', 'FullName'),
(2, 1, 'CAPTION', 'Full Name'),
(3, 1, 'REQUIRED', 'YES'),
(4, 1, 'SIZE', '20'),
(5, 1, 'MAXSIZE', ''),
(6, 1, 'VALIDATIONRULE', 'none'),
(7, 1, 'VALIDATIONMESSAGE', 'Please type your full name.'),
(8, 1, 'ADDITIONALATTRIBUTES', ''),
(9, 1, 'DEFAULTVALUE', ''),
(10, 1, 'DESCRIPTION', ''),
(11, 2, 'NAME', 'Header'),
(12, 2, 'TEXT', '<b>This text describes the form. It is added using the Free Text component</b>. HTML code can be added directly here.'),
(13, 3, 'NAME', 'Email'),
(14, 3, 'CAPTION', 'E-mail'),
(15, 3, 'REQUIRED', 'YES'),
(16, 3, 'SIZE', '20'),
(17, 3, 'MAXSIZE', ''),
(18, 3, 'VALIDATIONRULE', 'email'),
(19, 3, 'VALIDATIONMESSAGE', 'Invalid email address.'),
(20, 3, 'ADDITIONALATTRIBUTES', ''),
(21, 3, 'DEFAULTVALUE', ''),
(22, 3, 'DESCRIPTION', ''),
(23, 4, 'NAME', 'CompanySize'),
(24, 4, 'CAPTION', 'Number of Employees'),
(25, 4, 'SIZE', ''),
(26, 4, 'MULTIPLE', 'NO'),
(27, 4, 'ITEMS', '|Please Select[c]\n1-20\n21-50\n51-100\n>100|More than 100'),
(28, 4, 'REQUIRED', 'YES'),
(29, 4, 'ADDITIONALATTRIBUTES', ''),
(30, 4, 'DESCRIPTION', ''),
(31, 4, 'VALIDATIONMESSAGE', 'Please tell us how big is your company.'),
(32, 5, 'NAME', 'Position'),
(33, 5, 'CAPTION', 'Position'),
(34, 5, 'ITEMS', 'CEO\nCFO\nCTO\nHR[c]'),
(35, 5, 'FLOW', 'HORIZONTAL'),
(36, 5, 'REQUIRED', 'YES'),
(37, 5, 'ADDITIONALATTRIBUTES', ''),
(38, 5, 'DESCRIPTION', ''),
(39, 5, 'VALIDATIONMESSAGE', 'Please specify your position in the company'),
(40, 6, 'NAME', 'ContactBy'),
(41, 6, 'CAPTION', 'How should we contact you?'),
(42, 6, 'ITEMS', 'E-mail[c]\nPhone\nNewsletter[c]\nMail'),
(43, 6, 'FLOW', 'HORIZONTAL'),
(44, 6, 'REQUIRED', 'NO'),
(45, 6, 'ADDITIONALATTRIBUTES', ''),
(46, 6, 'DESCRIPTION', ''),
(47, 6, 'VALIDATIONMESSAGE', ''),
(48, 7, 'NAME', 'ContactWhen'),
(49, 7, 'CAPTION', 'When would you like to be contacted?'),
(50, 7, 'REQUIRED', 'YES'),
(51, 7, 'DATEFORMAT', 'dd.mm.yyyy'),
(52, 7, 'CALENDARLAYOUT', 'POPUP'),
(53, 7, 'ADDITIONALATTRIBUTES', ''),
(54, 7, 'READONLY', 'YES'),
(55, 7, 'POPUPLABEL', '...'),
(56, 7, 'DESCRIPTION', ''),
(57, 7, 'VALIDATIONMESSAGE', 'Please select a date when we should contact you.'),
(58, 8, 'NAME', 'Submit'),
(59, 8, 'LABEL', 'Submit'),
(60, 8, 'CAPTION', ''),
(61, 8, 'RESET', 'YES'),
(62, 8, 'RESETLABEL', 'Reset'),
(63, 8, 'ADDITIONALATTRIBUTES', ''),
(64, 9, 'NAME', 'Footer'),
(65, 9, 'TEXT', 'This form is an example. Please check our knowledgebase for articles related to how you should build your form. Articles are updated daily. <a href="http://www.rsjoomla.com/" target="_blank">http://www.rsjoomla.com/</a>');